### ISSUE TITLE
The PATH environment variable does not contain the path to ghc when using docker-compose

### ISSUE THREAD

**Issue by MrcJkb** [haskell/docker-haskell#63]
### How to reproduce
Given the following compose file

```
version: '2.3'

services:
  build:
    image: haskell:9.2.1
    volumes:
      - .:/usr/app
    command: bash -lc "printenv && cd /usr/app && cabal init"
```
When I run

```
COMPOSE_FILE=<name-of-compose-file>.yml docker-compose run --rm build
```

#### Epected
Then cabal initialises a project and /opt/ghc/9.2.1/bin is in the PATH environment variable that is printed

#### Actual
Then cabal fails with `The program 'ghc' version >=7.0.1 is required but it could not be found.`
And the PATH is printed as `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
